import { shuffleDeck } from '@/utils/helpers'

import { MUCH_NEEDED_REPAIRS_CARD_03, MUCH_NEEDED_REPAIRS_CARD_04 } from './cards/muchNeededRepairs'
import { FEAST_CARD_03, FEAST_CARD_04 } from './cards/feast'
import { FRESH_BATCH_CARD_03, FRESH_BATCH_CARD_04 } from './cards/freshBatch'
import { ENTRENCH_CARD_02, ENTRENCH_CARD_03, ENTRENCH_CARD_04 } from './cards/entrench'
import {
    ENHANCED_SYSTEMS_CARD_02,
    ENHANCED_SYSTEMS_CARD_03,
    ENHANCED_SYSTEMS_CARD_04,
} from './cards/enhancedSystems'
import { CARGO_DROP_CARD_02, CARGO_DROP_CARD_03, CARGO_DROP_CARD_04 } from './cards/cargoDrop'
import { GAMBIT_CARD, GAMBIT_CARD_02, GAMBIT_CARD_03, GAMBIT_CARD_04 } from './cards/gambit'
import {
    COMPETITION_KILLER_CARD,
    COMPETITION_KILLER_CARD_02,
    COMPETITION_KILLER_CARD_03,
    COMPETITION_KILLER_CARD_04,
} from './cards/competitionKiller'
import {
    SEVERE_STORM_CARD,
    SEVERE_STORM_CARD_02,
    SEVERE_STORM_CARD_03,
    SEVERE_STORM_CARD_04,
} from './cards/severeStorm'
import {
    INCENDIARY_BARRAGE_CARD,
    INCENDIARY_BARRAGE_CARD_02,
    INCENDIARY_BARRAGE_CARD_03,
    INCENDIARY_BARRAGE_CARD_04,
} from './cards/incendiaryBarrage'
import {
    FIREFIGHTERS_CARD,
    FIREFIGHTERS_CARD_02,
    FIREFIGHTERS_CARD_03,
    FIREFIGHTERS_CARD_04,
} from './cards/firefighters'
import {
    GENERATE_REVENUE_CARD_02,
    GENERATE_REVENUE_CARD_03,
    GENERATE_REVENUE_CARD_04,
} from './cards/generateRevenue'
import {
    BASE_DEFENSE_EVENT_CARD_02,
    BASE_DEFENSE_EVENT_CARD_03,
    BASE_DEFENSE_EVENT_CARD_04,
} from './cards/baseDefenseEvent'

const ALL_BASE_DEFENSE_CARDS = [
    MUCH_NEEDED_REPAIRS_CARD_03,
    MUCH_NEEDED_REPAIRS_CARD_04,

    FEAST_CARD_03,
    FEAST_CARD_04,

    FRESH_BATCH_CARD_03,
    FRESH_BATCH_CARD_04,

    ENTRENCH_CARD_02,
    ENTRENCH_CARD_03,
    ENTRENCH_CARD_04,

    ENHANCED_SYSTEMS_CARD_02,
    ENHANCED_SYSTEMS_CARD_03,
    ENHANCED_SYSTEMS_CARD_04,

    CARGO_DROP_CARD_02,
    CARGO_DROP_CARD_03,
    CARGO_DROP_CARD_04,

    COMPETITION_KILLER_CARD,
    COMPETITION_KILLER_CARD_02,
    COMPETITION_KILLER_CARD_03,
    COMPETITION_KILLER_CARD_04,

    INCENDIARY_BARRAGE_CARD,
    INCENDIARY_BARRAGE_CARD_02,
    INCENDIARY_BARRAGE_CARD_03,
    INCENDIARY_BARRAGE_CARD_04,

    FIREFIGHTERS_CARD,
    FIREFIGHTERS_CARD_02,
    FIREFIGHTERS_CARD_03,
    FIREFIGHTERS_CARD_04,

    GAMBIT_CARD,
    GAMBIT_CARD_02,
    GAMBIT_CARD_03,
    GAMBIT_CARD_04,

    GENERATE_REVENUE_CARD_02,
    GENERATE_REVENUE_CARD_03,
    GENERATE_REVENUE_CARD_04,

    BASE_DEFENSE_EVENT_CARD_02,
    BASE_DEFENSE_EVENT_CARD_03,
    BASE_DEFENSE_EVENT_CARD_04,

    SEVERE_STORM_CARD,
    SEVERE_STORM_CARD_02,
    SEVERE_STORM_CARD_03,
    SEVERE_STORM_CARD_04,
]

export const BASE_DEFENSE_CARDS = shuffleDeck(ALL_BASE_DEFENSE_CARDS)
