import { shuffleDeck } from '@/utils/helpers'

import {
    CLOSE_AIR_SUPPORT_CARD,
    CLOSE_AIR_SUPPORT_CARD_02,
    CLOSE_AIR_SUPPORT_CARD_03,
    CLOSE_AIR_SUPPORT_CARD_04,
} from './cards/closeAirSupport'
import {
    FLASHBANG_CARD,
    FLASHBANG_CARD_02,
    FLASHBANG_CARD_03,
    FLASHBANG_CARD_04,
} from './cards/flashbang'
import {
    SLICE_AND_DICE_CARD,
    SLICE_AND_DICE_CARD_02,
    SLICE_AND_DICE_CARD_03,
    SLICE_AND_DICE_CARD_04,
} from './cards/sliceAndDice'
import {
    SMOKE_GRENADE_CARD,
    SMOKE_GRENADE_CARD_02,
    SMOKE_GRENADE_CARD_03,
    SMOKE_GRENADE_CARD_04,
} from './cards/smokeGrenade'
import {
    SNAP_OUT_OF_IT_CARD_02,
    SNAP_OUT_OF_IT_CARD_03,
    SNAP_OUT_OF_IT_CARD_04,
} from './cards/snapOutOfIt'
import {
    TRUSTY_SIDEARM_CARD_02,
    TRUSTY_SIDEARM_CARD_03,
    TRUSTY_SIDEARM_CARD_04,
} from './cards/trustySidearm'
import {
    WALLBANG_CARD,
    WALLBANG_CARD_02,
    WALLBANG_CARD_03,
    WALLBANG_CARD_04,
} from './cards/wallbang'
import { MEDIVAC_CARD, MEDIVAC_CARD_02, MEDIVAC_CARD_03, MEDIVAC_CARD_04 } from './cards/medivac'
import { RPG_CARD, RPG_CARD_02, RPG_CARD_03, RPG_CARD_04 } from './cards/rpg'
import { DIG_IN_CARD, DIG_IN_CARD_02, DIG_IN_CARD_03, DIG_IN_CARD_04 } from './cards/digIn'
import {
    ATOMIC_RAGE_CARD,
    ATOMIC_RAGE_CARD_02,
    ATOMIC_RAGE_CARD_03,
    ATOMIC_RAGE_CARD_04,
} from './cards/atomicRage'
import {
    PANIC_BUTTON_CARD,
    PANIC_BUTTON_CARD_02,
    PANIC_BUTTON_CARD_03,
    PANIC_BUTTON_CARD_04,
} from './cards/panicButton'
import {
    THERMAL_SIGHTS_CARD,
    THERMAL_SIGHTS_CARD_02,
    THERMAL_SIGHTS_CARD_03,
    THERMAL_SIGHTS_CARD_04,
} from './cards/thermalSights'
import {
    FLAMING_BILE_CARD,
    FLAMING_BILE_CARD_02,
    FLAMING_BILE_CARD_03,
    FLAMING_BILE_CARD_04,
} from './cards/flamingBile'
import {
    BLAZING_SUN_CARD,
    BLAZING_SUN_CARD_02,
    BLAZING_SUN_CARD_03,
    BLAZING_SUN_CARD_04,
} from './cards/blazingSun'
import {
    DIZZIED_STRIKE_CARD,
    DIZZIED_STRIKE_CARD_02,
    DIZZIED_STRIKE_CARD_03,
    DIZZIED_STRIKE_CARD_04,
} from './cards/dizziedStrike'
import {
    FLAMETHROWER_CARD,
    FLAMETHROWER_CARD_02,
    FLAMETHROWER_CARD_03,
    FLAMETHROWER_CARD_04,
} from './cards/flamethrower'
import {
    LASER_SWORD_CARD,
    LASER_SWORD_CARD_02,
    LASER_SWORD_CARD_03,
    LASER_SWORD_CARD_04,
} from './cards/laserSword'
import {
    CRUEL_BLADE_CARD,
    CRUEL_BLADE_CARD_02,
    CRUEL_BLADE_CARD_03,
    CRUEL_BLADE_CARD_04,
} from './cards/cruelBlade'
import {
    ENERGY_BLAST_CARD,
    ENERGY_BLAST_CARD_02,
    ENERGY_BLAST_CARD_03,
    ENERGY_BLAST_CARD_04,
} from './cards/energyBlast'
import {
    GUIDED_MISSILE_CARD,
    GUIDED_MISSILE_CARD_02,
    GUIDED_MISSILE_CARD_03,
    GUIDED_MISSILE_CARD_04,
} from './cards/guidedMissile'
import {
    FULL_METAL_JACKET_CARD,
    FULL_METAL_JACKET_CARD_02,
    FULL_METAL_JACKET_CARD_03,
    FULL_METAL_JACKET_CARD_04,
} from './cards/fullMetalJacket'
import {
    FIRE_FLAIL_CARD,
    FIRE_FLAIL_CARD_02,
    FIRE_FLAIL_CARD_03,
    FIRE_FLAIL_CARD_04,
} from './cards/fireFlail'
import {
    MOBILE_SHIELD_BATTERY_CARD,
    MOBILE_SHIELD_BATTERY_CARD_02,
    MOBILE_SHIELD_BATTERY_CARD_03,
    MOBILE_SHIELD_BATTERY_CARD_04,
} from './cards/mobileShieldBattery'
import {
    SHATTERED_CARD,
    SHATTERED_CARD_02,
    SHATTERED_CARD_03,
    SHATTERED_CARD_04,
} from './cards/shattered'
import {
    STANDARD_ISSUE_RIFLE_CARD_03,
    STANDARD_ISSUE_RIFLE_CARD_04,
} from './cards/standardIssueRifle'
import {
    FRAG_GRENADE_CARD_02,
    FRAG_GRENADE_CARD_03,
    FRAG_GRENADE_CARD_04,
} from './cards/fragGrenade'
import {
    LASER_STRIKE_CARD_02,
    LASER_STRIKE_CARD_03,
    LASER_STRIKE_CARD_04,
} from './cards/laserStrike'
import {
    COMBAT_ARMOR_CARD,
    COMBAT_ARMOR_CARD_02,
    COMBAT_ARMOR_CARD_03,
    COMBAT_ARMOR_CARD_04,
} from './cards/combatArmor'
import {
    SHIELD_OVERLOAD_CARD,
    SHIELD_OVERLOAD_CARD_02,
    SHIELD_OVERLOAD_CARD_03,
    SHIELD_OVERLOAD_CARD_04,
} from './cards/shieldOverload'
import {
    VIOLENT_RUMINATIONS_CARD,
    VIOLENT_RUMINATIONS_CARD_02,
    VIOLENT_RUMINATIONS_CARD_03,
    VIOLENT_RUMINATIONS_CARD_04,
} from './cards/violentRuminations'

const ALL_COMBAT_CARDS = [
    ATOMIC_RAGE_CARD,
    ATOMIC_RAGE_CARD_02,
    ATOMIC_RAGE_CARD_03,
    ATOMIC_RAGE_CARD_04,

    BLAZING_SUN_CARD,
    BLAZING_SUN_CARD_02,
    BLAZING_SUN_CARD_03,
    BLAZING_SUN_CARD_04,

    CLOSE_AIR_SUPPORT_CARD,
    CLOSE_AIR_SUPPORT_CARD_02,
    CLOSE_AIR_SUPPORT_CARD_03,
    CLOSE_AIR_SUPPORT_CARD_04,

    COMBAT_ARMOR_CARD,
    COMBAT_ARMOR_CARD_02,
    COMBAT_ARMOR_CARD_03,
    COMBAT_ARMOR_CARD_04,

    CRUEL_BLADE_CARD,
    CRUEL_BLADE_CARD_02,
    CRUEL_BLADE_CARD_03,
    CRUEL_BLADE_CARD_04,

    DIG_IN_CARD,
    DIG_IN_CARD_02,
    DIG_IN_CARD_03,
    DIG_IN_CARD_04,

    DIZZIED_STRIKE_CARD,
    DIZZIED_STRIKE_CARD_02,
    DIZZIED_STRIKE_CARD_03,
    DIZZIED_STRIKE_CARD_04,

    ENERGY_BLAST_CARD,
    ENERGY_BLAST_CARD_02,
    ENERGY_BLAST_CARD_03,
    ENERGY_BLAST_CARD_04,

    FIRE_FLAIL_CARD,
    FIRE_FLAIL_CARD_02,
    FIRE_FLAIL_CARD_03,
    FIRE_FLAIL_CARD_04,

    FLAMETHROWER_CARD,
    FLAMETHROWER_CARD_02,
    FLAMETHROWER_CARD_03,
    FLAMETHROWER_CARD_04,

    FLAMING_BILE_CARD,
    FLAMING_BILE_CARD_02,
    FLAMING_BILE_CARD_03,
    FLAMING_BILE_CARD_04,

    FLASHBANG_CARD,
    FLASHBANG_CARD_02,
    FLASHBANG_CARD_03,
    FLASHBANG_CARD_04,

    FRAG_GRENADE_CARD_02,
    FRAG_GRENADE_CARD_03,
    FRAG_GRENADE_CARD_04,

    FULL_METAL_JACKET_CARD,
    FULL_METAL_JACKET_CARD_02,
    FULL_METAL_JACKET_CARD_03,
    FULL_METAL_JACKET_CARD_04,

    GUIDED_MISSILE_CARD,
    GUIDED_MISSILE_CARD_02,
    GUIDED_MISSILE_CARD_03,
    GUIDED_MISSILE_CARD_04,

    LASER_STRIKE_CARD_02,
    LASER_STRIKE_CARD_03,
    LASER_STRIKE_CARD_04,

    LASER_SWORD_CARD,
    LASER_SWORD_CARD_02,
    LASER_SWORD_CARD_03,
    LASER_SWORD_CARD_04,

    MEDIVAC_CARD,
    MEDIVAC_CARD_02,
    MEDIVAC_CARD_03,
    MEDIVAC_CARD_04,

    MOBILE_SHIELD_BATTERY_CARD,
    MOBILE_SHIELD_BATTERY_CARD_02,
    MOBILE_SHIELD_BATTERY_CARD_03,
    MOBILE_SHIELD_BATTERY_CARD_04,

    PANIC_BUTTON_CARD,
    PANIC_BUTTON_CARD_02,
    PANIC_BUTTON_CARD_03,
    PANIC_BUTTON_CARD_04,

    RPG_CARD,
    RPG_CARD_02,
    RPG_CARD_03,
    RPG_CARD_04,

    SHATTERED_CARD,
    SHATTERED_CARD_02,
    SHATTERED_CARD_03,
    SHATTERED_CARD_04,

    SHIELD_OVERLOAD_CARD,
    SHIELD_OVERLOAD_CARD_02,
    SHIELD_OVERLOAD_CARD_03,
    SHIELD_OVERLOAD_CARD_04,

    SLICE_AND_DICE_CARD,
    SLICE_AND_DICE_CARD_02,
    SLICE_AND_DICE_CARD_03,
    SLICE_AND_DICE_CARD_04,

    SMOKE_GRENADE_CARD,
    SMOKE_GRENADE_CARD_02,
    SMOKE_GRENADE_CARD_03,
    SMOKE_GRENADE_CARD_04,

    SNAP_OUT_OF_IT_CARD_02,
    SNAP_OUT_OF_IT_CARD_03,
    SNAP_OUT_OF_IT_CARD_04,

    STANDARD_ISSUE_RIFLE_CARD_03,
    STANDARD_ISSUE_RIFLE_CARD_04,

    THERMAL_SIGHTS_CARD,
    THERMAL_SIGHTS_CARD_02,
    THERMAL_SIGHTS_CARD_03,
    THERMAL_SIGHTS_CARD_04,

    TRUSTY_SIDEARM_CARD_02,
    TRUSTY_SIDEARM_CARD_03,
    TRUSTY_SIDEARM_CARD_04,

    VIOLENT_RUMINATIONS_CARD,
    VIOLENT_RUMINATIONS_CARD_02,
    VIOLENT_RUMINATIONS_CARD_03,
    VIOLENT_RUMINATIONS_CARD_04,

    WALLBANG_CARD,
    WALLBANG_CARD_02,
    WALLBANG_CARD_03,
    WALLBANG_CARD_04,
]

export const COMBAT_CARDS = shuffleDeck(ALL_COMBAT_CARDS)
